services:
  app:
    build:
      context: .
    command:
      - bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: neymar
      MONGO_INITDB_DATABASE: Flashcards
    ports:
      - "27017:27017"

  box:
    image: busybox:latest
    volumes:
      - /box

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: neymar
      ME_CONFIG_MONGODB_URL: mongodb://mongo-admin:neymar@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db

volumes:
  db:
  box: