GET http://localhost:8080/reactive-flashcards/users/677dccbc197c2812f6d3cd8a
Accept: application/json


###
POST http://localhost:8080/reactive-flashcards/users
Content-Type: application/json

{
  "name": "macaco",
  "email": "macaco@gmail.com"
}

###
POST http://localhost:8080/reactive-flashcards/users
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###
PUT http://localhost:8080/reactive-flashcards/users/677dccbc197c2812f6d3cd8a
Content-Type: application/json
Accept: application/json

{
  "name": "jamal",
  "email": "jamal@gmail.com"
}

###
DELETE http://localhost:8080/reactive-flashcards/users/677dccbc197c2812f6d3cd8a
