GET http://localhost:8080/reactive-flashcards/users/677dccbc197c2812f6d3cd8a
Accept: application/json


###
POST http://localhost:8080/reactive-flashcards/users
Content-Type: application/json

{
  "name": "macaco",
  "email": "macaco@gmail.com"
}

###
POST http://localhost:8080/reactive-flashcards/users
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###
PUT http://localhost:8080/reactive-flashcards/users/6781cc244553ae7199ac8bf4
Content-Type: application/json
Accept: application/json

{
  "name": "macaco",
  "email": "macaco@gmail.com"
}

###
DELETE http://localhost:8080/reactive-flashcards/users/677dccbc197c2812f6d3cd8a

###
POST http://localhost:8080/reactive-flashcards/decks
Content-Type: application/json

{
  "name": "estudo de inglês",
  "description": "deck para iniciantes",
  "cards": [
    {
      "front": "I doesn't have a decent meal in days!",
      "back": "Eu não tenho uma refeição decente em dias"
    },
    {
      "front": "The judge donned their oficial robes",
      "back": "Os juizes vestiram sua tunica oficial"
    },
    {
      "front": "To the man who can tell a history that has no end!",
      "back": "Ao homem que conseguir contar uma história que não tem fim!"
    }
  ]
}

###
GET http://localhost:8080/reactive-flashcards/decks
Accept: application/json

###
POST http://localhost:8080/reactive-flashcards/studies
Content-Type: application/json

{
  "deckId": "6784691449f7bc4f2d47d2b5",
  "userId": "6784690949f7bc4f2d47d2b4"
}

###
GET http://localhost:8080/reactive-flashcards/studies/6783140552e43668a630f334
Accept: application/json

###
GET http://localhost:8080/reactive-flashcards/studies/67846a567d2bc10fc5a62dbd/current-question
Accept: application/json

###
POST http://localhost:8080/reactive-flashcards/studies/67846a567d2bc10fc5a62dbd/answer
Content-Type: application/json

{
  "answer": "Eu não tenho uma refeição decente em dias"
}
